version: "3"
services:
    sportstore:
        build: .
        ports:
            - "8000:8000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "MyDatabase123@12"
            ACCEPT_EULA: "Y"