version: "3"
services:
    sportstore:
        build: .
        ports:
            - "8000:8000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - sqlserver
    sqlserver:
        image: "microsoft/mssql-server-windows-developer"
        environment:
            SA_PASSWORD: "MyDatabase123"
            ACCEPT_EULA: "Y"